### ISSUE TITLE
Default value in "add feature"

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#241]
Can we allow the user to specify what the default feature value is when adding a feature?

**Comment by mmcauliffe** [comment]
Whoops, thought this was for something else!

**Comment by mmcauliffe** [comment]
@kchall What I originally thought this was for was in the Add/edit segment dialog, you can now set all features to whatever value you want (like have them all be set to '+' and then change the ones you want), rather than have them all start at the default value for the feature system.  Might be better to have a way of changing the default value for a whole feature system, since it's currently inferred from all the feature values in the matrix, which might not be the desirable.
