### ISSUE TITLE
PrOD environment view

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#249]
The list of selected environments is truncated horizontally so that the full environment is not visible.

**Comment by kchall** [comment]
Also happens in the "phonological search" box.

**Comment by mmcauliffe** [comment]
I pushed a bunch of fixes to the master branch, see if they work well enough for you.  I might look into having a scrollbar for longer environments at some point, but it's a bit of a pain currently.  The latest version has the environments stretched as much as possible, and removed the ability of the segment pair widget to stretch, so that should make the environments visible unless you specify every feature or something.

**Comment by kchall** [comment]
Looks pretty good! It also seems like the "Enforce exhaustivity..." option could maybe wrap to two lines, to make the options box narrower? It's currently the longest of the three, which seems unnecessary. (And thanks in general for all of this -- I'll go through it all more carefully soon!)

**Comment by mmcauliffe** [comment]
This should be all good now
