### ISSUE TITLE
String similarity results

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#253]
1. The results window should probably have the column name be "result" instead of "similarity" because it could have been distance that was used. 

2. When string similarity is calculated on transcription instead of spelling, it used to show the transcriptions. This seems like a useful check?

**Comment by mmcauliffe** [comment]
Changed 1.  For 2, that was a conscious decision on my part, because I don't like the displaying of transcriptions in the table for two reasons.  Number one, it makes identifying the word harder, especially with the more opaque transcription systems like sampa and celex.  Number two, it makes later comparisons of metrics more difficult.  If you do a spelling-based one and then a transcription-based one, and then open the saved file up in R, you now have double the number of factors with the spelling and transcription both there.

Since the string type column explicitly says whether it's spelling or transcription or whatever, I feel like it doesn't make much sense to have the word columns be the transcriptions.  We also have a search function over the whole corpus, so if people need to look up what was actually compared to double check things, they can look it up via the spelling.  If you feel strongly about it, I can change it back, but I think it's more clear when it just uses spellings.
