### ISSUE TITLE
Acoustic Similarity GUI

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#256]
Automatically populate the fields for freq. limits and resolution with the defaults.

(Also: is there a reference I can add for the cross-correlation algorithm in the manual?)

**Comment by mmcauliffe** [comment]
I don't know if you need a specific reference for cross-correlation, it's a pretty standard time series analysis tool.  Numpy/scipy don't cite anything for it, and that's what we're using for it.  We could cite Natalie Lewandowski's thesis again for it, since that's where it was used for this particular purpose previously.

**Comment by kchall** [comment]
OK, thanks, will do (as a "see discussion in...").
