### ISSUE TITLE
more Gitksan

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#301]
Thanks for the widget fixes! But here's another error, this one once the Gitksan corpus has been opened:

![edit_word_gitksan](https://cloud.githubusercontent.com/assets/7317450/6014110/58b4df96-ab2c-11e4-8777-b5d17c300736.jpg)

**Comment by kchall** [comment]
Sorry, should have specified that this is when one tries to edit a word in the corpus.

**Comment by mmcauliffe** [comment]
I added some code to ignore those cases, but it's caused by the glottalized /n/ which is marked as +syllabic for some reason, so it tried to shove it into the vowel chart, but it doesn't have any features for vowels.  So if you fix that in your feature system, it should show up in the consonants like it's supposed to.
