### ISSUE TITLE
error messages in pop-up windows?

### ISSUE THREAD

**Issue by bhallen** [kchall/CorpusTools#342]
In neighborhood density, I received the error message "local variable 'q' referenced before assignment", but in a pop-up window rather than in the terminal. Consequently, there was no traceback information. If this moving of errors to their own windows is intentional, could we ensure that the original message still stays in the terminal as well, traceback and all?

**Comment by mmcauliffe** [comment]
It was intentional, it just wasn't done very well.  For binary applications (especially in Windows, not too sure about Mac), any exceptions thrown by the program and not handled (ie, ones that go to the terminal) crash the program.  I've added a better wrapper around them, that will get the traceback for the exception and display it in the details of the errorbox.  Hopefully it's a bit more informative now!
